# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
$terminal = uwsm app -- ghostty 
$browser = omarchy-launch-browser
bindd = SUPER SHIFT, Q, Close active window, killactive,

 bindd = SUPER, return, Terminal, exec,kitty #$terminal# --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
#bindd = SUPER, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
#bindd = SUPER, T, Activity, exec, $terminal -e btop
bindd = SUPER SHIFT, D , Docker, exec, $terminal -e lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER, Z, Chromium , exec, uwsm app -- zen-browser
# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
bindd = SUPER, Y, YouTube, exec, omarchy-launch-or-focus-webapp YouTube "https://youtube.com/"
bindd = SUPER SHIFT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER ALT, O, Normcap, exec, com.github.dynobo.normcap 
#bindd = SUPER CTRL , O, OCR Selection, exec, sh -c 'text=$(slurp | grim -g - - | tesseract stdin stdout -l eng); printf "%s" "$text" | wl-copy; notify-send -i "$noti_icon/clipboard.png" "Text Copied" "$text"' 


# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

#my bindings

#bindd = SUPER, L, hyprlock, exec, uwsm app -- hyprlock

#bindd = SUPER, W, vscodium, exec, uwsm app -- vscodium 
bindd = SUPER SHIFT, V, Clipboard, exec, walker -m clipboard


#bind = SUPER,  W, exec, vicinae toggle

