# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
     gaps_in = 2
     gaps_out = 4

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
     rounding = 0
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}


#animations: slipstream
#
# animations { 
# enabled = true
# bezier = myBezier, 0.05, 0.9, 0.1, 1.05
# animation = windows, 1, 6, myBezier
# animation = windowsIn, 1, 6, myBezier, slide
# animation = windowsOut, 1, 7, myBezier, slide
# animation = border, 1, 10, default
# animation = borderangle, 1, 8, default
# animation = fade, 1, 7, default
# animation = workspaces, 1, 3, myBezier, slide
#
# #rofi
# animation = layersIn, 1,  7, myBezier, slide
# }


#################SNOW BLACK###################
# animations {
#     enabled = yes
#     bezier = wind, 0.05, 0.9, 0.1, 1.05
#     bezier = winIn, 0.1, 1.1, 0.1, 1.1
#     bezier = winOut, 0.3, -0.3, 0, 1
#     bezier = liner, 1, 1, 1, 1
#     animation = windows, 1, 6, wind, slide
#     animation = windowsIn, 1, 6, winIn, slide
#     animation = windowsOut, 1, 5, winOut, slide
#     animation = windowsMove, 1, 5, wind, slide
#     animation = border, 1, 1, liner
#     animation = borderangle, 1, 30, liner, once
#     animation = fade, 1, 10, default
#     animation = workspaces, 1, 5, wind
#     animation = specialWorkspace, 1, 5, wind, slidevert
# }

#YouTube Musid Window Rule
windowrule {
    name = brave-yt-music-float
    match:class = ^(brave-browser|brave)$
    match:title = .*music\.youtube\.com.* - .*
    float = on
    center = on
    size = 800 600          # optional default size when floating
    rounding = 12           # optional rounded corners
}
