-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- Example: one or more Postgres connections
-- vim.g.dbs = {
--   dev = "postgresql://postgres:yourpassword@localhost:5432/your_dev_db",
--   prod = "postgresql://user:pass@host:5432/prod_db?sslmode=require",
--   -- Add as many as you want
-- -- }
--
-- return {
--   {
--     "tpope/vim-dadbod",
--     opt = true,
--     config = function()
--       vim.g.dbs = {
--         dev = "postgres://username:password@localhost:5432/coffee-shop",
--         prod = "postgres://username:password@production-host:5432/prod-coffee-shop",
--       }
--     end,
--   },
-- }
