include ~/.config/omarchy/current/theme/kitty.conf

# Font
#font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        12.0
## expirimental Font
 font_family  CaskaydiaMono Nerd Font
# font-style = Regular
# font-size = 13


# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
allow_remote_control yes

# Aesthetics
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor
enable_audio_bell no

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}


#font_size 13.0
scrollback_lines 10000
notify_on_cmd_finish invisible 20
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
confirm_os_window_close 0
cursor_shape block
url_style curly
remember_window_size no

#
# overlay_on_copy 1
# overlay_copy_format "✓ Copied {{ .num_chars }} characters"
# overlay_copy_animation fade-in-out
#
#
#
# status_bar_style single_line
# status_bar_component {
#     type osc52
#     content {{ Kitty: Copied {{ .num_chars }} chars to clipboard! }}
#     show_on_copy true
# }
#

